/**
 * Property 13: Ids are unique in the rendered document
 *
 * **Validates: Requirements 4.12**
 *
 * After rendering featured projects with `renderList`, ALL id attributes in the
 * document are unique (no duplicates). This includes both the static ids from
 * index.html (section ids, heading ids) and the dynamic ids generated by renderCard
 * (project-{id}-title). Multiple projects with different ids produce different
 * element ids in the DOM.
 */

import { describe, it, expect } from '@jest/globals';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import fc from 'fast-check';
import { validProject } from './generators.js';
import { createDocument } from './setup.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Set up jsdom globals before importing the module under test,
// because renderList uses the global `document.createDocumentFragment()`
const env = createDocument();
globalThis.document = env.document;

const projectsModulePath = resolve(__dirname, '..', 'js', 'modules', 'projects.js');
const { renderList } = await import(projectsModulePath);

describe('Property 13: Ids are unique in the rendered document', () => {
  let featuredTemplate, featuredList;

  beforeAll(() => {
    featuredTemplate = env.document.getElementById('featured-card-template');
    featuredList = env.document.querySelector('[data-featured-list]');
  });

  it('all id attributes in the document are unique after rendering featured projects', () => {
    fc.assert(
      fc.property(
        fc.uniqueArray(validProject('featured'), {
          minLength: 1,
          maxLength: 4,
          comparator: (a, b) => a.id === b.id,
        }),
        (projects) => {
          // Render projects into the featured list container
          renderList(projects, 'featured', featuredList, featuredTemplate);

          // Collect all elements with an id attribute in the entire document
          const allElements = env.document.querySelectorAll('[id]');
          const ids = Array.from(allElements).map((el) => el.getAttribute('id'));

          // Filter out empty ids (shouldn't exist, but guard against it)
          const nonEmptyIds = ids.filter((id) => id && id.trim() !== '');

          // Check for duplicates
          const seen = new Set();
          for (const id of nonEmptyIds) {
            expect(seen.has(id)).toBe(false);
            seen.add(id);
          }
        }
      ),
      { numRuns: 12 }
    );
  });

  it('dynamic project ids do not collide with static document ids', () => {
    fc.assert(
      fc.property(
        fc.uniqueArray(validProject('featured'), {
          minLength: 1,
          maxLength: 4,
          comparator: (a, b) => a.id === b.id,
        }),
        (projects) => {
          // Collect static ids before rendering
          renderList([], 'featured', featuredList, featuredTemplate);
          const staticElements = env.document.querySelectorAll('[id]');
          const staticIds = new Set(
            Array.from(staticElements)
              .map((el) => el.getAttribute('id'))
              .filter((id) => id && id.trim() !== '')
          );

          // Now render projects
          renderList(projects, 'featured', featuredList, featuredTemplate);

          // Get the dynamic ids generated by renderCard
          const dynamicIds = projects.map((p) => `project-${p.id}-title`);

          // No dynamic id should match any static id
          for (const dynId of dynamicIds) {
            expect(staticIds.has(dynId)).toBe(false);
          }
        }
      ),
      { numRuns: 12 }
    );
  });

  it('multiple projects with different ids produce different element ids', () => {
    fc.assert(
      fc.property(
        fc.uniqueArray(validProject('featured'), {
          minLength: 2,
          maxLength: 4,
          comparator: (a, b) => a.id === b.id,
        }),
        (projects) => {
          renderList(projects, 'featured', featuredList, featuredTemplate);

          // Each project generates a unique project-{id}-title element
          const titleIds = projects.map((p) => `project-${p.id}-title`);
          const titleIdSet = new Set(titleIds);

          // All generated ids must be distinct
          expect(titleIdSet.size).toBe(titleIds.length);

          // Each generated id must exist in the DOM exactly once
          for (const titleId of titleIds) {
            const matches = env.document.querySelectorAll(`[id="${titleId}"]`);
            expect(matches.length).toBe(1);
          }
        }
      ),
      { numRuns: 12 }
    );
  });
});
